apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- base/pv.yaml
- base/pvc.yaml
- base/configmap.yaml
- base/service.yaml
- all.yaml
patches:
- patch: |-
    apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      name: xnat-web
    spec:
      template:
        spec:
          containers:
          - name: xnat-web
            env:
            - name: CATALINA_OPTS
              value: "-Xms1000m -Xmx1000m -Dxnat.home=/data/xnat/home -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005"
            volumeMounts:
            - mountPath: /data/xnat/prearchive
              name: xnat-nfs
              subPath: data/prearchive
            - mountPath: /data/xnat/archive
              name: xnat-archive
            - mountPath: /data/xnat/build
              name: xnat-build
            - mountPath: /usr/local/share/xnat/plugins
              name: xnat-nfs
              readOnly: true
              subPath: plugins
            - mountPath: /usr/local/bin/init.sh
              name: init
              readOnly: true
              subPath: init.sh
            livenessProbe:
              $patch: delete
            readinessProbe:
              $patch: delete
            startupProbe:
              $patch: delete
          initContainers:
          - name: home-init
            command:
            - /usr/local/bin/init.sh
            volumeMounts:
            - mountPath: /usr/local/share/xnat/plugins
              name: xnat-nfs
              readOnly: true
              subPath: plugins
            - mountPath: /usr/local/bin/init.sh
              name: init
              readOnly: true
              subPath: init.sh
          volumes:
          - $patch: delete
            name: archive
          - $patch: delete
            name: prearchive
          - name: xnat-nfs
            persistentVolumeClaim:
              claimName: pv-xnat-nfs
          - name: xnat-archive
            persistentVolumeClaim:
              claimName: pv-xnat-archive
          - name: xnat-build
            persistentVolumeClaim:
              claimName: pv-xnat-build
          - name: init
            configMap:
              name: xnat-web-init
              defaultMode: 0555
              items:
              - key: init.sh
                path: init.sh
