apiVersion: v1
kind: ConfigMap
metadata:
  name: cvmfs-squid-config
  namespace: __NS__
  labels: { app: cvmfs-squid }
data:
  squid.conf: |
    http_port 3128

    acl Clients src __POD_CIDR__ __SVC_CIDR__
    acl CONNECT method CONNECT
    http_access allow Clients
    http_access deny CONNECT
    http_access deny all

    cache_mem 256 MB
    maximum_object_size 1024 MB
    maximum_object_size_in_memory 128 KB
    cache_dir aufs /var/spool/squid 50000 16 256
    cache_replacement_policy heap LFUDA
    memory_replacement_policy heap GDSF

    refresh_pattern -i /data/ 30000 100% 30000 override-expire override-lastmod ignore-no-store ignore-private
    refresh_pattern -i \.cvmfspublished$ 0 0% 0 ignore-no-store ignore-private
    refresh_pattern -i \.cvmfswhitelist$ 0 0% 0 ignore-no-store ignore-private
    refresh_pattern -i \.cvmfschecksum$ 0 0% 0 ignore-no-store ignore-private
    refresh_pattern . 30 20% 4320

    store_id_program /usr/lib/squid/storeid_file_rewrite /etc/squid/storeid.conf
    store_id_children 20 startup=10 idle=5 concurrency=0

    access_log /var/log/squid/access.log squid
    cache_log  /var/log/squid/cache.log
    cache_store_log none
    pid_filename /var/run/squid.pid
    coredump_dir /var/spool/squid

    forwarded_for delete
    via off

  storeid.conf: "^https?://[^/]+/cvmfs/(.*)$\thttp://cvmfs-canonical.local/cvmfs/$1\n"
