apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cvmfs-squid-cache
  namespace: __NS__
  labels: { app: cvmfs-squid }
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 60Gi
  storageClassName: __SC__
