apiVersion: v1
kind: PersistentVolume
metadata:
  name: xnat-nfs
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  mountOptions:
  - nfsvers=4.2
  storageClassName: nfs-csi
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: nfs-server.storage.svc.cluster.local/xnat##
    volumeAttributes:
      server: nfs-server.storage.svc.cluster.local
      share: /xnat
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: xnat-archive
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  mountOptions:
  - nfsvers=4.2
  storageClassName: nfs-csi
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: nfs-server.storage.svc.cluster.local/xnat/data/archive##
    volumeAttributes:
      server: nfs-server.storage.svc.cluster.local
      share: /xnat/data/archive
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: xnat-build
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  mountOptions:
  - nfsvers=4.2
  storageClassName: nfs-csi
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: nfs-server.storage.svc.cluster.local/xnat/data/build##
    volumeAttributes:
      server: nfs-server.storage.svc.cluster.local
      share: /xnat/data/build
