---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-xnat-nfs
spec:
  storageClassName: nfs-csi
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: xnat-nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-xnat-archive
spec:
  storageClassName: nfs-csi
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: xnat-archive
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-xnat-build
spec:
  storageClassName: nfs-csi
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: xnat-build
